const canvas=document.getElementById('game');const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;const W=canvas.width,H=canvas.height,ground=438;const keys={};const state={over:false,win:false,shake:0,particles:[],projectiles:[],texts:[]};const p={x:220,y:370,w:42,h:68,vx:0,vy:0,hp:100,max:100,face:1,onGround:true,attack:0,combo:0,cd1:0,cd2:0,cd3:0,ult:0,sub:2,inv:0};const e={x:740,y:320,w:86,h:118,vx:0,vy:0,hp:180,max:180,face:-1,onGround:true,attack:0,cd:70,stun:0,hit:0};
addEventListener('keydown',ev=>{keys[ev.key.toLowerCase()]=true;if(['j','k','l','i','o','w','a','d'].includes(ev.key.toLowerCase()))ev.preventDefault();if(ev.key.toLowerCase()==='j'&&!ev.repeat)attack();if(ev.key.toLowerCase()==='k'&&!ev.repeat)sling();if(ev.key.toLowerCase()==='l'&&!ev.repeat)dash();if(ev.key.toLowerCase()==='i'&&!ev.repeat)substitute();if(ev.key.toLowerCase()==='o'&&!ev.repeat)ultimate();});addEventListener('keyup',ev=>keys[ev.key.toLowerCase()]=false);
function hitbox(x,y,w,h){return{x,y,w,h}}function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}function hurt(dmg,source){if(p.inv>0)return;p.hp=Math.max(0,p.hp-dmg);p.inv=18;state.shake=5;pop(p.x,p.y-12,'-'+dmg);if(p.hp<=0)finish(false)}function damage(dmg){if(e.stun>0)return;e.hp=Math.max(0,e.hp-dmg);e.stun=10;e.hit=8;state.shake=4;pop(e.x+e.w/2,e.y-15,'-'+dmg);if(e.hp<=0)finish(true)}function pop(x,y,t){state.texts.push({x,y,t,life:38})}
function attack(){if(state.over||p.attack>0)return;p.attack=22;p.combo=p.combo%3+1;setTimeout(()=>{if(state.over)return;const reach=48+p.combo*12;const box=hitbox(p.x+(p.face>0?p.w:-reach),p.y+18,reach,48);if(overlap(box,hitbox(e.x,e.y,e.w,e.h)))damage(8+p.combo*3)},7)}function sling(){if(state.over||p.cd1>0)return;p.cd1=48;state.projectiles.push({x:p.x+p.w/2+p.face*20,y:p.y+28,vx:p.face*13,life:70});pop(p.x,p.y-18,'投石索');}function dash(){if(state.over||p.cd2>0)return;p.cd2=65;p.vx=p.face*11;p.inv=14;pop(p.x,p.y-18,'奔跑突进')}function substitute(){if(state.over||p.sub<=0)return;p.sub--;p.inv=40;p.x=Math.max(70,Math.min(W-120,p.x-p.face*100));pop(p.x,p.y-18,'替身')}function ultimate(){if(state.over||p.ult<100)return;p.ult=0;state.shake=14;flash();pop(p.x,p.y-25,'五块石头');setTimeout(()=>{if(!state.over)damage(58)},350)}
function finish(win){state.over=true;state.win=win;document.getElementById('resultTitle').textContent=win?'巨人倒下了':'倒在以拉谷';document.getElementById('resultCopy').textContent=win?'你刚刚经历了《撒母耳记上》第17章最核心的战斗之一。下一步，可以把“大卫”完整的人物成长线加入游戏。':'大卫不是无敌英雄。重新挑战，练习移动、投石索与替身的时机。';document.getElementById('result').classList.remove('hidden')}
function flash(){const f=document.getElementById('flash');f.animate([{opacity:.9},{opacity:0}],{duration:450});}
function reset(){Object.assign(p,{x:220,y:370,vx:0,vy:0,hp:100,attack:0,combo:0,cd1:0,cd2:0,ult:0,sub:2,inv:0});Object.assign(e,{x:740,y:320,vx:0,vy:0,hp:180,cd:70,stun:0,hit:0});state.over=false;state.win=false;state.projectiles=[];state.particles=[];state.texts=[];document.getElementById('result').classList.add('hidden')}
document.getElementById('restartBtn').onclick=reset;document.getElementById('storyBtn').onclick=()=>document.getElementById('storyDialog').showModal();document.getElementById('closeDialog').onclick=()=>document.getElementById('storyDialog').close();document.getElementById('verseBtn').onclick=()=>document.getElementById('storyDialog').showModal();
function update(){if(!state.over){p.inv=Math.max(0,p.inv-1);p.attack=Math.max(0,p.attack-1);p.cd1=Math.max(0,p.cd1-1);p.cd2=Math.max(0,p.cd2-1);if(keys.a)p.vx=-4.5;if(keys.d)p.vx=4.5;if(!keys.a&&!keys.d)p.vx*=.72;if(p.vx!==0)p.face=Math.sign(p.vx);if(keys.w&&p.onGround){p.vy=-11;p.onGround=false}p.vy+=.55;p.x+=p.vx;p.y+=p.vy;if(p.y+p.h>=ground){p.y=ground-p.h;p.vy=0;p.onGround=true}p.x=Math.max(30,Math.min(W-p.w-30,p.x));p.ult=Math.min(100,p.ult+.06);
if(e.stun>0)e.stun--;if(e.hit>0)e.hit--;e.cd--;if(e.cd<=0&&!e.stun){e.cd=75;const dist=p.x-e.x;if(Math.abs(dist)<150){e.vx=Math.sign(dist)*2.3;if(Math.abs(dist)<95){hurt(8);e.cd=50}}else e.vx=Math.sign(dist)*1.2}e.vy+=.55;e.x+=e.vx;e.y+=e.vy;if(e.y+e.h>=ground){e.y=ground-e.h;e.vy=0;e.onGround=true}e.x=Math.max(380,Math.min(W-e.w-30,e.x));
state.projectiles.forEach(q=>{q.x+=q.vx;q.life--;if(q.life>0&&overlap(hitbox(q.x-6,q.y-6,12,12),hitbox(e.x,e.y,e.w,e.h))){damage(20);q.life=0;p.ult=Math.min(100,p.ult+22)}});state.projectiles=state.projectiles.filter(q=>q.life>0);state.particles.forEach(x=>{x.x+=x.vx;x.y+=x.vy;x.vy+=.08;x.life--});state.particles=state.particles.filter(x=>x.life>0);state.texts.forEach(x=>{x.y-=.6;x.life--});state.texts=state.texts.filter(x=>x.life>0)}updateHud()}
function updateHud(){document.getElementById('playerHpText').textContent=`${Math.ceil(p.hp)} / ${p.max}`;document.getElementById('enemyHpText').textContent=`${Math.ceil(e.hp)} / ${e.max}`;document.getElementById('playerHpBar').style.width=`${p.hp}%`;document.getElementById('enemyHpBar').style.width=`${e.hp/e.max*100}%`}
function draw(){ctx.save();if(state.shake>0){ctx.translate((Math.random()-.5)*state.shake,(Math.random()-.5)*state.shake);state.shake--}drawBg();drawProjectiles();drawCharacter(p,'david');drawCharacter(e,'goliath');drawParticles();drawTexts();ctx.restore();requestAnimationFrame(()=>{update();draw()})}
function drawBg(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#8c7152');g.addColorStop(.6,'#c39b61');g.addColorStop(1,'#6e4b2d');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#5a3c25';ctx.fillRect(0,ground,W,H-ground);ctx.fillStyle='#755337';for(let i=0;i<9;i++){ctx.beginPath();ctx.moveTo(i*130,ground);ctx.lineTo(i*130+50,300+Math.sin(i)*35);ctx.lineTo(i*130+110,ground);ctx.fill()}ctx.fillStyle='#4d341f';ctx.fillRect(0,ground,W,5);ctx.fillStyle='#dac092';ctx.font='bold 14px Georgia';ctx.fillText('ELAH VALLEY',38,145);ctx.fillStyle='#f0dcb6';ctx.font='bold 11px sans-serif';ctx.fillText('以 拉 谷',40,163);}
function drawCharacter(o,type){const flash=o.inv>0&&Math.floor(o.inv/3)%2===0;if(flash)return;ctx.save();ctx.translate(Math.round(o.x+o.w/2),Math.round(o.y+o.h));ctx.scale(o.face,1);if(type==='david'){ctx.fillStyle='#273d32';ctx.fillRect(-17,-54,34,46);ctx.fillStyle='#caa477';ctx.fillRect(-13,-77,26,23);ctx.fillStyle='#3b2418';ctx.fillRect(-15,-82,30,9);ctx.fillStyle='#9a7043';ctx.fillRect(-21,-10,10,10);ctx.fillRect(11,-10,10,10);ctx.fillStyle='#d5b37b';ctx.fillRect(13,-48,18,5);if(p.attack>0){ctx.fillStyle='#b9a06e';ctx.fillRect(18,-50,30,5)}}else{ctx.fillStyle='#57483c';ctx.fillRect(-35,-105,70,88);ctx.fillStyle='#a88b65';ctx.fillRect(-28,-130,56,34);ctx.fillStyle='#342d27';ctx.fillRect(-32,-137,64,12);ctx.fillStyle='#5c4c3d';ctx.fillRect(-48,-70,18,54);ctx.fillRect(30,-70,18,54);ctx.fillStyle='#3a3028';ctx.fillRect(-29,-17,21,17);ctx.fillRect(8,-17,21,17)}ctx.restore()}
function drawProjectiles(){state.projectiles.forEach(q=>{ctx.fillStyle='#30271e';ctx.beginPath();ctx.arc(q.x,q.y,6,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#e2c17c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(q.x-18,q.y);ctx.lineTo(q.x+18,q.y);ctx.stroke()})}function drawParticles(){state.particles.forEach(x=>{ctx.fillStyle=x.c;ctx.fillRect(x.x,x.y,3,3)})}function drawTexts(){ctx.font='bold 14px sans-serif';ctx.textAlign='center';state.texts.forEach(x=>{ctx.fillStyle='#fff3d2';ctx.globalAlpha=Math.max(0,x.life/38);ctx.fillText(x.t,x.x,x.y)});ctx.globalAlpha=1;ctx.textAlign='left'}
setInterval(()=>{if(state.over)return;for(let i=0;i<3;i++)state.particles.push({x:Math.random()*W,y:ground-5,vx:(Math.random()-.5)*.7,vy:-Math.random()*1.2,life:30+Math.random()*30,c:'#c9a66b'})},120);draw();
