const C=document.querySelector('#game'),X=C.getContext('2d');X.imageSmoothingEnabled=false;const W=960,H=540,G=438,Q=Object.create(null);
const K={david:[100,4.8,11.4,1,'投石索','奔跑突进','五块石头'],moses:[115,4,10.6,1.04,'杖击','分海步','红海'],samson:[128,3.7,10,1.22,'驴腮骨','巨力突进','推柱'],daniel:[108,4.15,10.9,.97,'祷告','狮坑步','封住狮口'],elijah:[99,4.45,11.1,1.08,'火焰','先知步','从天降火'],paul:[101,5,11.6,.99,'书信','宣教奔行','宣教旅程']};
const S={pick:{p1:null,p2:null},run:0,over:0,round:1,score:[0,0],count:0,fx:[],shots:[],txt:[],rings:[],slow:0,shake:0};let A,B;
const $=i=>document.getElementById(i),cl=(v,a,b)=>Math.max(a,Math.min(b,v)),hb=(x,y,w,h)=>({x,y,w,h}),ov=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y,foe=f=>f.slot==='p1'?B:A;
function mk(slot,id,x,f){const k=K[id];return{slot,id,x,y:G-68,w:42,h:68,f,hp:k[0],max:k[0],sp:k[1],jp:k[2],pw:k[3],skill:k[4],dash:k[5],ult:k[6],cdS:0,cdD:0,u:0,sub:2,inv:0,st:0,lock:0,step:0,last:0,combo:0,ct:0,atk:0,air:0,protect:0}}
function popup(x,y,t,k='n'){S.txt.push({x,y,t,l:42,k})}function burst(x,y,n,c='#d6b36e',p=3){for(let i=0;i<n;i++)S.fx.push({x,y,vx:(Math.random()-.5)*p,vy:(Math.random()-.9)*p,l:18+Math.random()*24,c})}function ring(x,y,r,c='#e7c47e'){S.rings.push({x,y,r,l:18,c})}function msg(t){const e=$('centerMessage');e.textContent=t;e.classList.remove('show');void e.offsetWidth;e.classList.add('show')}
function pickUI(){for(const [id,s] of [['p1Grid','p1'],['p2Grid','p2']]){const g=$(id);g.innerHTML='';Object.values(BIBLE_ROSTER).forEach(c=>{const b=document.createElement('button');b.className='char-card '+(S.pick[s]===c.id?'selected':'');b.innerHTML=`<div class="avatar ${c.id}">${c.name[0]}</div><div class="char-main"><strong>${c.name}</strong><span>${c.role}</span><small>${c.anchor}</small></div><i>${S.pick[s]===c.id?'READY':'选择'}</i>`;b.onclick=()=>{S.pick[s]=c.id;pickUI();$('startBtn').disabled=!(S.pick.p1&&S.pick.p2)};g.appendChild(b)})$(s+'Label').textContent=S.pick[s]?BIBLE_ROSTER[S.pick[s]].name:'未选择'}}
function clean(){S.fx=[];S.shots=[];S.txt=[];S.rings=[];S.slow=0;S.shake=0}
function initRound(){clean();S.over=0;S.run=0;S.count=3;A=mk('p1',S.pick.p1,210,1);B=mk('p2',S.pick.p2,708,-1);$('result').classList.add('hidden');msg(`${S.round} · 3`);let n=3;const tick=()=>{if(S.over)return;n--;S.count=n;if(n>0){msg(String(n));setTimeout(tick,650)}else{msg('FIGHT!');S.run=1}};setTimeout(tick,650)}
function start(){if(!S.pick.p1||!S.pick.p2)return;S.round=1;S.score=[0,0];$('selectScreen').classList.add('hidden');$('battleScreen').classList.remove('hidden');meta();initRound()}
function selectBack(){S.run=0;$('battleScreen').classList.add('hidden');$('selectScreen').classList.remove('hidden');$('result').classList.add('hidden');pickUI()}
function rematch(){S.round=1;S.score=[0,0];initRound()}
function act(slot,a){const f=slot==='p1'?A:B;if(!f)return;if(a==='a')atk(f);if(a==='s')skill(f);if(a==='d')dash(f);if(a==='r')sub(f);if(a==='u')ult(f)}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();Q[k]=1;const m={j:['p1','a'],k:['p1','s'],l:['p1','d'],i:['p1','r'],o:['p1','u'],1:['p2','a'],2:['p2','s'],3:['p2','d'],4:['p2','r'],5:['p2','u']}[k];if(m)act(m[0],m[1])});addEventListener('keyup',e=>Q[e.key.toLowerCase()]=0);
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>(e.preventDefault(),Q[k]=1);b.onpointerup=b.onpointercancel=b.onpointerleave=e=>(e.preventDefault(),Q[k]=0)});document.querySelectorAll('[data-action]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();const z=b.dataset.action.split('-');act(z[0],{attack:'a',skill:'s',dash:'d',sub:'r',ult:'u'}[z[1]])});
function atk(f){if(!S.run||f.st>0||f.lock>0)return;const now=performance.now();if(now-f.last>620)f.step=0;f.last=now;f.step=f.step%5+1;f.lock=12;f.atk=18;const n=f.step;setTimeout(()=>{if(!S.run||f.st>0)return;const e=foe(f),r=n>=4?72:56,b=hb(f.x+(f.f>0?40:-r),f.y+9,r,58);if(ov(b,hb(e.x,e.y,e.w,e.h)))hit(f,e,[0,6,7,9,11,14][n]*f.pw,n===5?16:8,n===5?15:7,'普攻')},46)}
function skill(f){if(!S.run||f.st>0||f.cdS>0)return;f.cdS=42;const e=foe(f),c={x:f.x+21,y:f.y+32};popup(c.x,c.y-18,f.skill,'s');if(['david','paul'].includes(f.id))S.shots.push({o:f,x:c.x+f.f*22,y:c.y,v:f.f*(f.id==='paul'?13:15),l:56,k:'stone'});else if(f.id==='elijah')S.shots.push({o:f,x:c.x+f.f*20,y:c.y-24,v:f.f*9,vy:-1,l:42,k:'fire'});else if(f.id==='moses')melee(f,e,18,94,'杖击');else if(f.id==='samson')melee(f,e,23,112,'爆发');else{f.inv=Math.max(f.inv,28);f.protect=24;f.u=cl(f.u+12,0,100);ring(c.x,c.y,34,'#c6d6ea')}}
function melee(f,e,d,r,label){const b=hb(f.x+(f.f>0?26:-r),f.y-12,r,92);if(ov(b,hb(e.x,e.y,e.w,e.h)))hit(f,e,d*f.pw,17,13,label);burst(f.x+21+f.f*45,f.y+25,12,f.f>0?'#d8bb82':'#b38d65',3)}
function dash(f){if(!S.run||f.st>0||f.cdD>0)return;f.cdD=56;f.inv=16;f.vx=f.f*13;popup(f.x,f.y-14,f.dash,'s');const e=foe(f);setTimeout(()=>{if(S.run&&ov(hb(f.x+(f.f>0?28:-98),f.y+8,98,56),hb(e.x,e.y,e.w,e.h)))hit(f,e,12*f.pw,10,10,'冲锋')},38)}
function sub(f){if(!S.run||f.sub<=0)return;f.sub--;f.inv=46;const ox=f.x;f.x=cl(f.x-f.f*132,40,W-f.w-40);burst(ox+21,f.y+34,15,'#c5b697',3);ring(f.x+21,f.y+34,28);popup(f.x,f.y-14,'替身','s')}
function ult(f){if(!S.run||f.st>0||f.u<100)return;f.u=0;S.slow=18;S.shake=15;msg(f.ult);const e=foe(f),d={david:60,moses:62,samson:68,daniel:56,elijah:64,paul:58}[f.id]||58;setTimeout(()=>{if(!S.run)return;hit(f,e,d*f.pw,28,26,'奥义');burst(e.x+21,e.y+34,34,'#f5d37f',5);ring(e.x+21,e.y+34,58)},320)}
function hit(f,e,d,st,kn,label){if(!S.run||e.inv>0)return;e.hp=cl(e.hp-d,0,e.max);e.st=st;e.vx+=f.f*kn;e.vy=-2.2;e.air=Math.min(18,e.air+st);f.combo++;f.ct=52;e.combo=0;e.ct=0;f.u=cl(f.u+(d>25?11:4),0,100);S.shake=Math.max(S.shake,d>25?10:4);popup(e.x+21,e.y-12,'-'+Math.ceil(d),'d');popup(e.x+21,e.y+82,label,'s');burst(e.x+21,e.y+32,d>25?20:8,d>25?'#f5d37f':'#d8bc84',3.5);if(e.hp<=0)roundWin(f)}
function roundWin(f){if(S.over)return;S.over=1;S.run=0;S.score[f.slot==='p1'?0:1]++;msg(`${f.slot==='p1'?'P1':'P2'} WIN`);if(S.score[0]>=2||S.score[1]>=2){$('resultTitle').textContent=`${f.slot==='p1'?'P1':'P2'} 胜利 · ${BIBLE_ROSTER[f.id].name}`;$('resultCopy').textContent=`Best of 3 · ${S.score[0]}-${S.score[1]}`;setTimeout(()=>$('result').classList.remove('hidden'),420)}else{S.round++;setTimeout(initRound,900)}}
function update(f,dt){f.inv=Math.max(0,f.inv-dt);f.st=Math.max(0,f.st-dt);f.lock=Math.max(0,f.lock-dt);f.cdS=Math.max(0,f.cdS-dt);f.cdD=Math.max(0,f.cdD-dt);f.ct=Math.max(0,f.ct-1);if(f.ct<=0)f.combo=0;if(f.st<=0){const l=Q[f.slot==='p1'?'a':'arrowleft'],r=Q[f.slot==='p1'?'d':'arrowright'];if(l&&!r)f.vx=-f.sp;else if(r&&!l)f.vx=f.sp;else f.vx*=.74;if(Math.abs(f.vx)>.1)f.f=Math.sign(f.vx);const j=f.slot==='p1'?'w':'arrowup';if(Q[j]&&f.on){f.vy=-f.jp;f.on=0;Q[j]=0}}else f.vx*=.78;f.vy+=.58*dt;f.x+=f.vx*dt;f.y+=f.vy*dt;if(f.y+f.h>=G){f.y=G-f.h;f.vy=0;f.on=1;f.air=0}f.x=cl(f.x,24,W-f.w-24);f.u=cl(f.u+.028*dt,0,100)}
function shots(dt){for(const q of S.shots){q.x+=q.v*dt;q.y+=(q.vy||0)*dt;q.l-=dt;const t=q.o.slot==='p1'?B:A;if(q.l>0&&ov(hb(q.x-8,q.y-8,16,16),hb(t.x,t.y,t.w,t.h))){hit(q.o,t,(q.k==='fire'?24:20)*q.o.pw,14,11,q.k==='fire'?'火焰':'精准');q.l=0}}S.shots=S.shots.filter(q=>q.l>0&&q.x>-50&&q.x<W+50)}
function fx(){for(const p of S.fx){p.x+=p.vx;p.y+=p.vy;p.vy+=.09;p.l--}S.fx=S.fx.filter(p=>p.l>0);for(const t of S.txt){t.y-=.55;t.l--}S.txt=S.txt.filter(t=>t.l>0);for(const r of S.rings){r.r+=2.5;r.l--}S.rings=S.rings.filter(r=>r.l>0)}
function hud(){if(!A||!B)return;$('p1Name').textContent=`P1 · ${BIBLE_ROSTER[A.id].name}`;$('p2Name').textContent=`P2 · ${BIBLE_ROSTER[B.id].name}`;$('p1HpText').textContent=`${Math.ceil(A.hp)} / ${A.max}`;$('p2HpText').textContent=`${Math.ceil(B.hp)} / ${B.max}`;$('p1HpBar').style.width=`${A.hp/A.max*100}%`;$('p2HpBar').style.width=`${B.hp/B.max*100}%`;$('p1UltBar').style.width=`${A.u}%`;$('p2UltBar').style.width=`${B.u}%`;$('p1Combo').classList.toggle('show',A.combo>1);$('p2Combo').classList.toggle('show',B.combo>1);$('p1Combo').querySelector('strong').textContent=A.combo;$('p2Combo').querySelector('strong').textContent=B.combo;document.querySelector('.round-info b').textContent=S.count>0?`准备 · ${S.count}`:`第 ${S.round} 回合`;document.querySelector('.round-info small').textContent=`BO3 · ${S.score[0]}-${S.score[1]}`}
function meta(){const a=BIBLE_ROSTER[A.id],b=BIBLE_ROSTER[B.id];$('fightLoreTitle').textContent=`${a.name} vs ${b.name}`;$('fightLore').innerHTML=`<div><b>${a.name}</b><span>${a.role}</span><small>${a.facts.join(' · ')}</small><em>${a.anchor}</em></div><div><b>${b.name}</b><span>${b.role}</span><small>${b.facts.join(' · ')}</small><em>${b.anchor}</em></div>`}
function arena(){const g=X.createLinearGradient(0,0,0,H);g.addColorStop(0,'#171c25');g.addColorStop(.6,'#727b7e');g.addColorStop(1,'#2f271f');X.fillStyle=g;X.fillRect(0,0,W,H);X.fillStyle='#b7ab94';X.globalAlpha=.2;for(let i=0;i<7;i++){X.beginPath();X.moveTo(i*170,G);X.lineTo(i*170+75,310+Math.sin(i)*25);X.lineTo(i*170+150,G);X.fill()}X.globalAlpha=1;X.fillStyle='#4d3927';X.fillRect(0,G,W,H-G);X.fillStyle='#735739';X.fillRect(0,G,W,6);X.strokeStyle='#dfc47f55';X.setLineDash([4,8]);X.beginPath();X.moveTo(W/2,G-120);X.lineTo(W/2,G);X.stroke();X.setLineDash([])}
function draw(f){if(f.inv>0&&Math.floor(f.inv/3)%2===0)return;X.save();X.translate(f.x+21,f.y+68);X.scale(f.f,1);X.fillStyle='#0007';X.beginPath();X.ellipse(0,2,29,7,0,0,7);X.fill();X.fillStyle=f.id==='david'?'#314439':f.id==='moses'?'#6d7068':f.id==='samson'?'#584737':f.id==='daniel'?'#4e4152':f.id==='elijah'?'#49352a':'#5f6254';X.fillRect(-18,-58,36,50);X.fillStyle='#c9a477';X.fillRect(-13,-81,26,23);X.fillStyle='#40342a';X.fillRect(-16,-87,32,10);if(f.id==='moses'){X.strokeStyle='#b99e70';X.lineWidth=4;X.beginPath();X.moveTo(22,-56);X.lineTo(27,-5);X.stroke()}if(f.id==='samson'){X.fillStyle='#2d231c';X.fillRect(-25,-88,50,20)}if(f.atk>0){X.fillStyle='#f2d69d';X.fillRect(16,-53,30,4)}X.restore()}
function drawFX(){for(const q of S.shots){X.fillStyle=q.k==='fire'?'#e28e4e':'#2e261d';X.beginPath();X.arc(q.x,q.y,6,0,7);X.fill();X.strokeStyle=q.k==='fire'?'#f1bd63':'#e2c17c';X.beginPath();X.moveTo(q.x-18,q.y);X.lineTo(q.x+18,q.y);X.stroke()}for(const r of S.rings){X.globalAlpha=r.l/18;X.strokeStyle=r.c;X.beginPath();X.arc(r.x,r.y,r.r,0,7);X.stroke()}X.globalAlpha=1;for(const p of S.fx){X.fillStyle=p.c;X.fillRect(p.x,p.y,3,3)}X.font='bold 14px sans-serif';X.textAlign='center';for(const t of S.txt){X.globalAlpha=Math.max(0,t.l/42);X.fillStyle=t.k==='d'?'#ffe7a3':t.k==='s'?'#f4ddb0':'#ffb7a3';X.fillText(t.t,t.x,t.y)}X.globalAlpha=1;X.textAlign='left'}
function loop(){requestAnimationFrame(loop);const dt=Math.min(1.5,1);if(S.run){const sc=S.slow>0?.35:1;S.slow=Math.max(0,S.slow-dt);update(A,dt*sc);update(B,dt*sc);shots(dt*sc)}fx();S.shake=Math.max(0,S.shake-dt);hud();X.save();if(S.shake)X.translate((Math.random()-.5)*S.shake,(Math.random()-.5)*S.shake);arena();if(A)draw(A);if(B)draw(B);drawFX();X.restore()}
$('startBtn').onclick=start;$('rematchBtn').onclick=rematch;$('changeBtn').onclick=selectBack;$('aboutBtn').onclick=()=>$('aboutDialog').showModal();$('closeAbout').onclick=()=>$('aboutDialog').close();pickUI();loop();
