const C=document.querySelector('#game'),X=C.getContext('2d');X.imageSmoothingEnabled=false;const W=960,H=540,G=438,Q=Object.create(null);
const K={
 david:{hp:100,sp:4.8,jp:11.4,pw:1,sk1:'投石索',sk2:'牧者突进',ul:'五块石头',c:'#c7ad71'},
 moses:{hp:115,sp:4,jp:10.6,pw:1.04,sk1:'杖击',sk2:'红海之路',ul:'红海',c:'#91a6b1'},
 samson:{hp:128,sp:3.7,jp:10,pw:1.22,sk1:'驴腮骨',sk2:'城门突击',ul:'推柱',c:'#a68561'},
 daniel:{hp:108,sp:4.15,jp:10.9,pw:.97,sk1:'祷告',sk2:'狮子坑',ul:'封住狮口',c:'#8fa0b9'},
 elijah:{hp:99,sp:4.45,jp:11.1,pw:1.08,sk1:'火焰',sk2:'迦密山',ul:'从天降火',c:'#be7650'},
 paul:{hp:101,sp:5,jp:11.6,pw:.99,sk1:'书信',sk2:'宣讲',ul:'宣教旅程',c:'#859879'}
};
const S={pick:{p1:null,p2:null,sc1:'fire',sc2:'water',h1:'michael',h2:'elijah'},run:0,over:0,r:1,score:[0,0],cnt:0,fx:[],shot:[],txt:[],ring:[],shake:0,slow:0,used:{p1:0,p2:0}};let A,B;
const $=id=>document.getElementById(id),cl=(v,a,b)=>Math.max(a,Math.min(b,v)),hb=(x,y,w,h)=>({x,y,w,h}),ov=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y,opp=f=>f.slot==='p1'?B:A;
function fighter(slot,id,x,face,scroll,helper){const k=K[id];return{slot,id,x,y:G-68,w:42,h:68,face,hp:k.hp,max:k.hp,sp:k.sp,jp:k.jp,pw:k.pw,c:k.c,sk1:k.sk1,sk2:k.sk2,ul:k.ul,cd1:0,cd2:0,scrollCd:0,u:0,sub:1,subCd:0,inv:0,st:0,lock:0,step:0,last:0,combo:0,ct:0,atk:0,air:0,protect:0,armor:0,scroll,helper,helperUsed:S.used[slot]}}
function say(t){const e=$('centerMessage');if(!e)return;e.textContent=t;e.classList.remove('show');void e.offsetWidth;e.classList.add('show')}
function txt(x,y,t,k='n'){S.txt.push({x,y,t,l:40,k})}function burst(x,y,n,c='#d6b36e',p=3){for(let i=0;i<n;i++)S.fx.push({x,y,vx:(Math.random()-.5)*p,vy:(Math.random()-.9)*p,l:18+Math.random()*24,c})}function ring(x,y,r,c='#e7c47e'){S.ring.push({x,y,r,l:18,c})}
function normalizeUI(){document.querySelectorAll('.touch-skills button').forEach(b=>{const a=b.dataset.action||'';if(a.includes('-skill'))b.textContent='技1';if(a.includes('-dash'))b.textContent='技2'});const n=document.querySelector('.arena-hint');if(n)n.textContent='P1：WASD + J K L I O / 6 7    P2：方向键 + 1 2 3 4 5 / 8 9'}
function refreshSelect(){for(const [gid,s] of [['p1Grid','p1'],['p2Grid','p2']]){const g=$(gid);g.innerHTML='';Object.values(BIBLE_ROSTER).forEach(c=>{const b=document.createElement('button');b.className='char-card '+(S.pick[s]===c.id?'selected':'');b.innerHTML=`<div class="avatar ${c.id}">${c.name[0]}</div><div class="char-main"><strong>${c.name}</strong><span>${c.role}</span><small>${c.anchor}</small></div><i>${S.pick[s]===c.id?'READY':'选择'}</i>`;b.onclick=()=>{S.pick[s]=c.id;refreshSelect();$('startBtn').disabled=!(S.pick.p1&&S.pick.p2)};g.appendChild(b)})$(s+'Label').textContent=S.pick[s]?BIBLE_ROSTER[S.pick[s]].name:'未选择'}[['p1Scroll','sc1'],['p2Scroll','sc2'],['p1Helper','h1'],['p2Helper','h2']].forEach(([id,key])=>{const e=$(id),src=key[0]==='s'?BIBLE_SUPPORTS.scrolls:BIBLE_SUPPORTS.helpers;if(!e||!src)return;e.innerHTML='';Object.entries(src).forEach(([v,c])=>{const o=document.createElement('option');o.value=v;o.textContent=c.name;e.appendChild(o)});e.value=S.pick[key]})}
function clean(){S.fx=[];S.shot=[];S.txt=[];S.ring=[];S.shake=0;S.slow=0}
function newRound(){clean();S.over=0;S.run=0;S.cnt=3;A=fighter('p1',S.pick.p1,205,1,S.pick.sc1,S.pick.h1);B=fighter('p2',S.pick.p2,713,-1,S.pick.sc2,S.pick.h2);$('result').classList.add('hidden');say(`${S.r} · 3`);let n=3;const tick=()=>{if(S.over)return;n--;S.cnt=n;if(n){say(n);setTimeout(tick,620)}else{say('FIGHT!');S.run=1}};setTimeout(tick,620)}
function start(){if(!S.pick.p1||!S.pick.p2)return;S.r=1;S.score=[0,0];S.used={p1:0,p2:0};S.pick.sc1=$('p1Scroll')?.value||S.pick.sc1;S.pick.sc2=$('p2Scroll')?.value||S.pick.sc2;S.pick.h1=$('p1Helper')?.value||S.pick.h1;S.pick.h2=$('p2Helper')?.value||S.pick.h2;$('selectScreen').classList.add('hidden');$('battleScreen').classList.remove('hidden');meta();newRound()}
function rematch(){S.r=1;S.score=[0,0];S.used={p1:0,p2:0};newRound()}function back(){S.run=0;$('battleScreen').classList.add('hidden');$('selectScreen').classList.remove('hidden');$('result').classList.add('hidden');refreshSelect()}
function act(s,a){const f=s==='p1'?A:B;if(!f)return;({a:attack,s1:skill1,s2:skill2,d:skill2,r:sub,u:ult,c:scroll,h:helper}[a]||(()=>{}))(f)}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();Q[k]=1;const m={j:['p1','a'],k:['p1','s1'],l:['p1','s2'],i:['p1','r'],o:['p1','u'],6:['p1','c'],7:['p1','h'],1:['p2','a'],2:['p2','s1'],3:['p2','s2'],4:['p2','r'],5:['p2','u'],8:['p2','c'],9:['p2','h']}[k];if(m)act(...m)});addEventListener('keyup',e=>Q[e.key.toLowerCase()]=0);
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>(e.preventDefault(),Q[k]=1);b.onpointerup=b.onpointercancel=b.onpointerleave=e=>(e.preventDefault(),Q[k]=0)});
document.querySelectorAll('[data-action]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();const [s,a]=b.dataset.action.split('-');act(s,a==='skill'?'s1':a==='dash'?'s2':a==='skill1'?'s1':a==='skill2'?'s2':a==='attack'?'a':a==='sub'?'r':a==='ult'?'u':a==='scroll'?'c':'h')});
function attack(f){if(!S.run||f.st||f.lock)return;const now=performance.now();if(now-f.last>540)f.step=0;f.last=now;f.step=f.step%4+1;f.lock=11;f.atk=16;const n=f.step;setTimeout(()=>{if(!S.run||f.st)return;const e=opp(f),r=n===4?78:58,b=hb(f.x+(f.face>0?40:-r),f.y+8,r,58);if(ov(b,hb(e.x,e.y,e.w,e.h)))hit(f,e,[0,6,7,9,12][n]*f.pw,n===4?18:8,n===4?16:7,'普攻')},38)}
function skill1(f){if(!S.run||f.st||f.cd1>0)return;f.cd1=46;const e=opp(f),c={x:f.x+21,y:f.y+30};txt(c.x,c.y-18,f.sk1,'s');if(f.id==='david')S.shot.push({o:f,x:c.x+f.face*24,y:c.y,v:f.face*15,l:52,k:'shot1'});else if(f.id==='moses')melee(f,e,18,96,'杖击',16);else if(f.id==='samson')melee(f,e,24,112,'驴腮骨',19);else if(f.id==='daniel'){f.inv=34;f.protect=20;txt(c.x,c.y+15,'不妥协','support');ring(c.x,c.y,38,'#b8c9de')}else if(f.id==='elijah')S.shot.push({o:f,x:c.x+f.face*24,y:c.y-20,v:f.face*10,vy:-.7,l:50,k:'fire1'});else if(f.id==='paul')S.shot.push({o:f,x:c.x+f.face*24,y:c.y,v:f.face*14,l:50,k:'letter'})}
function skill2(f){if(!S.run||f.st||f.cd2>0)return;f.cd2=64;const e=opp(f),c={x:f.x+21,y:f.y+30};txt(c.x,c.y-18,f.sk2,'s');if(f.id==='david'){f.inv=12;f.vx=f.face*12;setTimeout(()=>{if(S.run)melee(f,e,20,92,'牧者突进',18)},40)}else if(f.id==='moses'){S.shot.push({o:f,x:c.x+f.face*25,y:c.y+5,v:f.face*9,l:58,k:'water'})}else if(f.id==='samson'){f.inv=10;f.vx=f.face*14;setTimeout(()=>{if(S.run)melee(f,e,28,125,'城门突击',20)},52)}else if(f.id==='daniel'){f.inv=12;ring(c.x+f.face*55,c.y,58,'#9eafca');setTimeout(()=>{if(S.run){const b=hb(f.x+(f.face>0?30:-110),f.y-18,110,98);if(ov(b,hb(e.x,e.y,e.w,e.h)))hit(f,e,22,21,17,'狮坑')}} ,100)}else if(f.id==='elijah'){for(let i=0;i<3;i++)setTimeout(()=>S.shot.push({o:f,x:f.x+21+f.face*(30+i*20),y:f.y-15-i*18,v:f.face*7,l:35,k:'fire2'}),i*65)}else if(f.id==='paul'){f.vx=f.face*12;setTimeout(()=>{if(S.run)melee(f,e,18,105,'宣讲',14)},42)}}
function melee(f,e,d,r,label,kn){const b=hb(f.x+(f.face>0?26:-r),f.y-12,r,94);if(ov(b,hb(e.x,e.y,e.w,e.h)))hit(f,e,d*f.pw,17,kn,label);burst(f.x+21+f.face*45,f.y+25,12,f.c,3)}
function sub(f){if(!S.run||f.st||f.sub<=0||f.subCd>0||f.u<1)return;f.sub--;f.u--;f.subCd=600;f.inv=34;const ox=f.x;f.x=cl(f.x-f.face*132,35,W-f.w-35);burst(ox+21,f.y+34,16,'#c5b697',3);ring(f.x+21,f.y+34,28);txt(f.x,f.y-14,'替身','support')}
function scroll(f){if(!S.run||f.st||f.scrollCd>0)return;const s=BIBLE_SUPPORTS.scrolls[f.scroll];f.scrollCd=s.cd;f.armor=38;txt(f.x+21,f.y-20,s.name,'support');burst(f.x+21,f.y+34,18,s.color,4);ring(f.x+f.face*55,f.y+28,44,s.color);const e=opp(f);if(f.scroll==='fire')S.shot.push({o:f,x:f.x+21+f.face*28,y:f.y+18,v:f.face*11,l:60,k:'scrollFire'});else if(f.scroll==='water'){ring(f.x+21,f.y+34,58,s.color)}else if(f.scroll==='wind'){const b=hb(f.x+(f.face>0?25:-135),f.y-20,135,100);if(ov(b,hb(e.x,e.y,e.w,e.h)))hit(f,e,24*f.pw,22,18,'风压')}else{const b=hb(f.x+(f.face>0?25:-90),f.y-12,90,96);if(ov(b,hb(e.x,e.y,e.w,e.h)))hit(f,e,16*f.pw,20,8,'土流壁')}}
function helper(f){if(!S.run||f.helperUsed)return;f.helperUsed=1;S.used[f.slot]=1;const h=BIBLE_SUPPORTS.helpers[f.helper],e=opp(f);txt(f.x+21,f.y-35,h.name,'support');burst(f.x+21,f.y+24,15,h.color,4);if(f.helper==='michael'||f.helper==='samson'){const b=hb(f.x+(f.face>0?25:-105),f.y-5,105,88);if(ov(b,hb(e.x,e.y,e.w,e.h)))hit(f,e,26,22,18,'帮手')}else if(f.helper==='elijah')S.shot.push({o:f,x:f.x+21+f.face*24,y:f.y+4,v:f.face*10,l:48,k:'helperFire'});else if(f.helper==='paul')S.shot.push({o:f,x:f.x+21+f.face*24,y:f.y+26,v:f.face*13,l:46,k:'helperNote'});else S.shot.push({o:f,x:f.x+21+f.face*24,y:f.y+28,v:f.face*15,l:42,k:'helperStone'})}
function ult(f){if(!S.run||f.st||f.u<4)return;f.u=0;S.slow=18;S.shake=15;say(f.ul);const e=opp(f),d={david:62,moses:64,samson:70,daniel:58,elijah:66,paul:60}[f.id]*f.pw;setTimeout(()=>{if(S.run)hit(f,e,d,30,28,'奥义')},300)}
function hit(f,e,d,st,kn,label){if(!S.run||e.inv||e.armor>0)return;e.hp=cl(e.hp-d,0,e.max);e.st=st;e.vx+=f.face*kn;e.vy=-2.4;f.u=Math.min(4,f.u+(d>25?1:0));f.combo++;f.ct=48;e.combo=0;e.ct=0;e.air=Math.min(24,e.air+st);S.shake=Math.max(S.shake,d>25?10:4);txt(e.x+21,e.y-12,'-'+Math.ceil(d),'d');txt(e.x+21,e.y+82,label,'s');burst(e.x+21,e.y+32,d>25?20:8,d>25?'#f5d37f':f.c,3.5);if(e.combo>20){e.protect=24;e.st=0;e.vx*=.25;txt(e.x+21,e.y-32,'保护','support')}if(e.hp<=0)win(f)}
function win(f){if(S.over)return;S.over=1;S.run=0;const i=f.slot==='p1'?0:1;S.score[i]++;say(`${f.slot==='p1'?'P1':'P2'} WIN`);if(S.score[i]>=2){$('resultTitle').textContent=`${f.slot==='p1'?'P1':'P2'} 胜利 · ${BIBLE_ROSTER[f.id].name}`;$('resultCopy').textContent=`Best of 3 · ${S.score[0]}-${S.score[1]}`;setTimeout(()=>$('result').classList.remove('hidden'),420)}else{S.r++;setTimeout(newRound,900)}}
function update(f,dt){f.inv=Math.max(0,f.inv-dt);f.st=Math.max(0,f.st-dt);f.lock=Math.max(0,f.lock-dt);f.cd1=Math.max(0,f.cd1-dt);f.cd2=Math.max(0,f.cd2-dt);f.scrollCd=Math.max(0,f.scrollCd-dt);f.subCd=Math.max(0,f.subCd-dt);f.armor=Math.max(0,f.armor-dt);f.protect=Math.max(0,f.protect-dt);f.ct=Math.max(0,f.ct-1);f.atk=Math.max(0,f.atk-1);if(f.ct<=0)f.combo=0;if(f.st<=0){const l=Q[f.slot==='p1'?'a':'arrowleft'],r=Q[f.slot==='p1'?'d':'arrowright'];if(l&&!r)f.vx=-f.sp;else if(r&&!l)f.vx=f.sp;else f.vx*=.74;if(Math.abs(f.vx)>.1)f.face=Math.sign(f.vx);const j=f.slot==='p1'?'w':'arrowup';if(Q[j]&&f.on){f.vy=-f.jp;f.on=0;Q[j]=0}}else f.vx*=.78;f.vy+=.58*dt;f.x+=f.vx*dt;f.y+=f.vy*dt;if(f.y+f.h>=G){f.y=G-f.h;f.vy=0;f.on=1;f.air=0}f.x=cl(f.x,24,W-f.w-24);if(f.hp<=f.max*.35)f.pw=Math.min(f.pw*1.0005,1.12)}
function shots(dt){for(const q of S.shot){q.x+=q.v*dt;q.y+=(q.vy||0)*dt;q.l-=dt;const t=q.o.slot==='p1'?B:A;if(q.l>0&&ov(hb(q.x-9,q.y-9,18,18),hb(t.x,t.y,t.w,t.h))){hit(q.o,t,(q.k==='fire'||q.k==='fire1'||q.k==='fire2'||q.k==='scrollFire'||q.k==='helperFire')?26:(q.k==='helperNote'?18:20)*q.o.pw,14,11,q.k.startsWith('helper')?'帮手':'技能');q.l=0}}S.shot=S.shot.filter(q=>q.l>0&&q.x>-50&&q.x<W+50)}
function fx(){for(const p of S.fx){p.x+=p.vx;p.y+=p.vy;p.vy+=.09;p.l--}S.fx=S.fx.filter(p=>p.l>0);for(const t of S.txt){t.y-=.55;t.l--}S.txt=S.txt.filter(t=>t.l>0);for(const r of S.ring){r.r+=2.5;r.l--}S.ring=S.ring.filter(r=>r.l>0)}
function hud(){if(!A||!B)return;[['p1Name',`P1 · ${BIBLE_ROSTER[A.id].name}`],['p2Name',`P2 · ${BIBLE_ROSTER[B.id].name}`],['p1HpText',`${Math.ceil(A.hp)} / ${A.max}`],['p2HpText',`${Math.ceil(B.hp)} / ${B.max}`]].forEach(([i,v])=>$(i).textContent=v);$('p1HpBar').style.width=`${A.hp/A.max*100}%`;$('p2HpBar').style.width=`${B.hp/B.max*100}%`;$('p1UltBar').style.width=`${A.u/4*100}%`;$('p2UltBar').style.width=`${B.u/4*100}%`;$('p1Combo').classList.toggle('show',A.combo>1);$('p2Combo').classList.toggle('show',B.combo>1);$('p1Combo').querySelector('strong').textContent=A.combo;$('p2Combo').querySelector('strong').textContent=B.combo;document.querySelector('.round-info b').textContent=S.cnt?`准备 · ${S.cnt}`:`第 ${S.r} 回合`;document.querySelector('.round-info small').textContent=`BO3 · ${S.score[0]}-${S.score[1]}`}
function meta(){const a=BIBLE_ROSTER[A.id],b=BIBLE_ROSTER[B.id];$('fightLoreTitle').textContent=`${a.name} vs ${b.name}`;$('fightLore').innerHTML=`<div><b>${a.name}</b><span>${a.role}</span><small>${a.facts.join(' · ')}</small><em>${a.anchor}</em></div><div><b>${b.name}</b><span>${b.role}</span><small>${b.facts.join(' · ')}</small><em>${b.anchor}</em></div>`;const c=document.querySelector('.control-note');if(c)c.textContent='P1 WASD + J/K/L/I/O/6/7 · P2 方向键 + 1/2/3/4/5/8/9 · 普攻 / 技能1 / 技能2 / 替身 / 奥义 / 密卷 / 帮手'}
function arena(){const g=X.createLinearGradient(0,0,0,H);g.addColorStop(0,'#171c25');g.addColorStop(.6,'#727b7e');g.addColorStop(1,'#2f271f');X.fillStyle=g;X.fillRect(0,0,W,H);X.fillStyle='#b7ab94';X.globalAlpha=.2;for(let i=0;i<7;i++){X.beginPath();X.moveTo(i*170,G);X.lineTo(i*170+75,310+Math.sin(i)*25);X.lineTo(i*170+150,G);X.fill()}X.globalAlpha=1;X.fillStyle='#4d3927';X.fillRect(0,G,W,H-G);X.fillStyle='#735739';X.fillRect(0,G,W,6);X.strokeStyle='#dfc47f55';X.setLineDash([4,8]);X.beginPath();X.moveTo(W/2,G-120);X.lineTo(W/2,G);X.stroke();X.setLineDash([])}
function draw(f){if(f.inv>0&&Math.floor(f.inv/3)%2===0)return;X.save();X.translate(f.x+21,f.y+68);X.scale(f.face,1);X.fillStyle='#0007';X.beginPath();X.ellipse(0,2,29,7,0,0,7);X.fill();X.fillStyle=f.c;X.fillRect(-18,-58,36,50);X.fillStyle='#c9a477';X.fillRect(-13,-81,26,23);X.fillStyle='#40342a';X.fillRect(-16,-87,32,10);if(f.id==='samson'){X.fillStyle='#2d231c';X.fillRect(-25,-88,50,20)}if(f.atk>0){X.fillStyle='#f2d69d';X.fillRect(16,-53,32,4)}if(f.armor>0){X.strokeStyle='#fff0ad';X.lineWidth=3;X.beginPath();X.arc(0,-38,38,0,Math.PI*2);X.stroke()}if(f.subCd>0){X.fillStyle='#d6b36e';X.font='9px sans-serif';X.fillText(Math.ceil(f.subCd/60)+'s',-10,-96)}X.restore()}
function drawFx(){for(const q of S.shot){X.fillStyle=q.k.includes('fire')?'#e28e4e':q.k.includes('water')?'#71a9c8':'#2e261d';X.beginPath();X.arc(q.x,q.y,6,0,7);X.fill();X.strokeStyle=q.k.includes('helper')?'#e5d0a2':q.k.includes('scroll')?'#d6b36e':'#e2c17c';X.beginPath();X.moveTo(q.x-18,q.y);X.lineTo(q.x+18,q.y);X.stroke()}for(const r of S.ring){X.globalAlpha=r.l/18;X.strokeStyle=r.c;X.lineWidth=2;X.beginPath();X.arc(r.x,r.y,r.r,0,7);X.stroke()}X.globalAlpha=1;for(const p of S.fx){X.fillStyle=p.c;X.fillRect(p.x,p.y,3,3)}X.font='bold 14px sans-serif';X.textAlign='center';for(const t of S.txt){X.globalAlpha=Math.max(0,t.l/40);X.fillStyle=t.k==='d'?'#ffe4a0':t.k==='support'?'#9ee3f0':'#f4ddb0';X.fillText(t.t,t.x,t.y)}X.globalAlpha=1;X.textAlign='left'}
function loop(){if(S.run){const s=S.slow>0?.45:1;update(A,s);update(B,s);shots(s);S.slow=Math.max(0,S.slow-s)}fx();hud();X.save();if(S.shake)X.translate((Math.random()-.5)*S.shake,(Math.random()-.5)*S.shake);arena();if(A)draw(A);if(B)draw(B);drawFx();X.restore();if(S.shake)S.shake--;requestAnimationFrame(loop)}
$('startBtn').onclick=start;$('rematchBtn').onclick=rematch;$('changeBtn').onclick=back;$('aboutBtn').onclick=()=>$('aboutDialog').showModal();$('closeAbout').onclick=()=>$('aboutDialog').close();normalizeUI();refreshSelect();loop();