const C=document.querySelector('#game'),X=C.getContext('2d');X.imageSmoothingEnabled=false;const W=960,H=540,G=438,K={david:[100,4.8,11.4,1,'投石索','奔跑突进','五块石头'],moses:[115,4,10.6,1.04,'杖击','分海步','红海'],samson:[128,3.7,10,1.22,'驴腮骨','巨力突进','推柱'],daniel:[108,4.15,10.9,.97,'祷告','狮坑步','封住狮口'],elijah:[99,4.45,11.1,1.08,'火焰','先知步','从天降火'],paul:[101,5,11.6,.99,'书信','宣教奔行','宣教旅程']};const key=Object.create(null),S={pick:{p1:null,p2:null},run:0,over:0,r:1,sc:[0,0],fx:[],shot:[],txt:[],ring:[]};let A,B;
const $=i=>document.getElementById(i),cl=(v,a,b)=>Math.max(a,Math.min(b,v)),hb=(x,y,w,h)=>({x,y,w,h}),ov=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function mk(s,id,x,f){let k=K[id];return{slot:s,id,x,y:G-68,w:42,h:68,f,hp:k[0],max:k[0],sp:k[1],jp:k[2],pw:k[3],cd1:0,cd2:0,u:0,sub:2,inv:0,st:0,lock:0,step:0,last:0,combo:0,ct:0,atk:0}}
function txt(x,y,t,k='n'){S.txt.push({x,y,t,l:36,k})}function burst(x,y,n,c='#d6b36e',p=3){for(let i=0;i<n;i++)S.fx.push({x,y,vx:(Math.random()-.5)*p,vy:(Math.random()-.9)*p,l:20+Math.random()*20,c})}function rr(x,y,r,c='#e7c47e'){S.ring.push({x,y,r,l:16,c})}function say(t){let e=$('centerMessage');e.textContent=t;e.classList.remove('show');void e.offsetWidth;e.classList.add('show')}function later(f,m){setTimeout(f,m)}
function picks(){for(let [gid,slot] of [['p1Grid','p1'],['p2Grid','p2']]){let g=$(gid);g.innerHTML='';Object.values(BIBLE_ROSTER).forEach(c=>{let b=document.createElement('button');b.className='char-card '+(S.pick[slot]===c.id?'selected':'');b.innerHTML=`<div class="avatar ${c.id}">${c.name[0]}</div><div class="char-main"><strong>${c.name}</strong><span>${c.role}</span><small>${c.anchor}</small></div><i>${S.pick[slot]===c.id?'READY':'选择'}</i>`;b.onclick=()=>{S.pick[slot]=c.id;picks();$('startBtn').disabled=!(S.pick.p1&&S.pick.p2)};g.appendChild(b)})$(slot+'Label').textContent=S.pick[slot]?BIBLE_ROSTER[S.pick[slot]].name:'未选择'}}
function resetRound(){S.fx=[];S.shot=[];S.txt=[];S.ring=[];S.over=0;S.run=1;A=mk('p1',S.pick.p1,205,1);B=mk('p2',S.pick.p2,713,-1);$('result').classList.add('hidden');say('ROUND '+S.r)}function start(){if(!S.pick.p1||!S.pick.p2)return;S.r=1;S.sc=[0,0];$('selectScreen').classList.add('hidden');$('battleScreen').classList.remove('hidden');meta();resetRound()}function select(){S.run=0;$('battleScreen').classList.add('hidden');$('selectScreen').classList.remove('hidden');$('result').classList.add('hidden');picks()}function rematch(){S.sc=[0,0];S.r=1;resetRound()}function foe(f){return f.slot==='p1'?B:A}function act(s,t){let f=s==='p1'?A:B;if(!f)return;t==='a'&&atk(f);t==='s'&&skill(f);t==='d'&&dash(f);t==='r'&&sub(f);t==='u'&&ult(f)}
addEventListener('keydown',e=>{let k=e.key.toLowerCase();key[k]=1;let m={j:['p1','a'],k:['p1','s'],l:['p1','d'],i:['p1','r'],o:['p1','u'],1:['p2','a'],2:['p2','s'],3:['p2','d'],4:['p2','r'],5:['p2','u']}[k];if(m)act(m[0],m[1])});addEventListener('keyup',e=>key[e.key.toLowerCase()]=0);
document.querySelectorAll('[data-key]').forEach(b=>{let k=b.dataset.key;b.onpointerdown=e=>(e.preventDefault(),key[k]=1);b.onpointerup=b.onpointercancel=b.onpointerleave=e=>(e.preventDefault(),key[k]=0)});document.querySelectorAll('[data-action]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();let z=b.dataset.action.split('-');act(z[0],{attack:'a',skill:'s',dash:'d',sub:'r',ult:'u'}[z[1]])});
function atk(f){if(!S.run||f.st>0||f.lock>0)return;let now=performance.now();if(now-f.last>620)f.step=0;f.last=now;f.step=f.step%5+1;f.lock=13;f.atk=18;let n=f.step;later(()=>{if(!S.run||f.st>0)return;let e=foe(f),r=K[f.id][4]?56:56,b=hb(f.x+(f.f>0?40:-r),f.y+10,r,58);if(ov(b,hb(e.x,e.y,e.w,e.h)))hit(f,e,[0,6,7,9,11,14][n]*f.pw,n===5?15:8,n===5?14:7,'普攻')},48)}
function skill(f){if(!S.run||f.st>0||f.cd1>0)return;f.cd1=44;let e=foe(f),c={x:f.x+21,y:f.y+34},z=K[f.id];txt(c.x,c.y-18,z[4],'s');if(['david','paul'].includes(f.id))S.shot.push({o:f,x:c.x+f.f*22,y:c.y,v:f.f*(f.id==='paul'?13:15),l:55,k:'p'});else if(f.id==='elijah')S.shot.push({o:f,x:c.x+f.f*20,y:c.y-25,v:f.f*9,vy:-1,l:42,k:'fire'});else if(f.id==='moses')melee(f,e,18,'杖击',92);else if(f.id==='samson')melee(f,e,23,'爆发',110);else f.inv=30}
function melee(f,e,dmg,label,r){let b=hb(f.x+(f.f>0?26:-r),f.y-12,r,90);if(ov(b,hb(e.x,e.y,e.w,e.h)))hit(f,e,dmg*f.pw,17,12,label);burst(f.x+f.w/2+f.f*45,f.y+25,12,f.f>0?'#d8bb82':'#b38d65',3)}
function dash(f){if(!S.run||f.st>0||f.cd2>0)return;f.cd2=58;f.inv=16;f.vx=f.f*13;txt(f.x,f.y-14,K[f.id][5],'s');let e=foe(f);later(()=>melee(f,e,12,'冲锋',98),35)}function sub(f){if(!S.run||!f.sub)return;f.sub--;f.inv=45;f.x=cl(f.x-f.f*130,40,W-f.w-40);rr(f.x+21,f.y+34,28);txt(f.x,f.y-14,'替身','s')}function ult(f){if(!S.run||f.st>0||f.u<100)return;f.u=0;say(K[f.id][6]);let e=foe(f),d=({david:60,moses:62,samson:68,daniel:56,elijah:64,paul:58}[f.id]||58)*f.pw;later(()=>{hit(f,e,d,28,25,'奥义');burst(e.x+21,e.y+34,30,'#f5d37f',5);rr(e.x+21,e.y+34,54,f.id==='elijah'?'#d56b42':'#e4c57e')},300)}
function hit(f,e,dmg,st,kn,label){if(!S.run||e.inv>0)return;e.hp=cl(e.hp-dmg,0,e.max);e.st=st;e.vx+=f.f*kn;e.vy=-2;f.u=cl(f.u+(dmg>25?11:4),0,100);f.combo++;f.ct=48;e.combo=0;S.hit=0.3;burst(e.x+21,e.y+30,dmg>25?18:8,dmg>25?'#f5d37f':K[f.id][4],3.5);txt(e.x+21,e.y-12,'-'+Math.ceil(dmg),'d');txt(e.x+21,e.y+80,label,'s');if(e.hp<=0)win(f)}
function win(f){if(S.over)return;S.over=1;S.run=0;S.sc[f.slot==='p1'?0:1]++;if(S.sc[f.slot==='p1'?0:1]>=2){$('resultTitle').textContent=`${f.slot==='p1'?'P1':'P2'} 胜利 · ${BIBLE_ROSTER[f.id].name}`;$('resultCopy').textContent=`比分 ${S.sc[0]}-${S.sc[1]} · Best of 3`;later(()=>$('result').classList.remove('hidden'),300)}else{S.r++;later(resetRound,800)}}
function updateF(f,dt){f.inv=Math.max(0,f.inv-dt);f.st=Math.max(0,f.st-dt);f.lock=Math.max(0,f.lock-dt);f.atk=Math.max(0,f.atk-dt);f.cd1=Math.max(0,f.cd1-dt);f.cd2=Math.max(0,f.cd2-dt);f.ct=Math.max(0,f.ct-1);if(f.ct<=0)f.combo=0;if(f.st<=0){let l=key[f.slot==='p1'?'a':'arrowleft'],r=key[f.slot==='p1'?'d':'arrowright'];if(l&&!r)f.vx=-f.spd;else if(r&&!l)f.vx=f.spd;else f.vx*=.74;if(Math.abs(f.vx)>.1)f.f=Math.sign(f.vx);let j=f.slot==='p1'?'w':'arrowup';if(key[j]&&f.on){f.vy=-f.jp;f.on=0;key[j]=0}}else f.vx*=.78;f.vy+=.58*dt;f.x+=f.vx*dt;f.y+=f.vy*dt;if(f.y+68>=G){f.y=G-68;f.vy=0;f.on=1}f.x=cl(f.x,24,W-66);f.u=cl(f.u+.028*dt,0,100)}
function shots(dt){for(let q of S.shot){q.x+=q.v*dt;q.y+=(q.vy||0)*dt;q.l-=dt;let t=q.o.slot==='p1'?B:A;if(q.l>0&&ov(hb(q.x-8,q.y-8,16,16),hb(t.x,t.y,t.w,t.h))){hit(q.o,t,(q.k==='fire'?24:20)*q.o.pw,13,11,q.k==='fire'?'火焰':'精准');q.l=0}}S.shot=S.shot.filter(q=>q.l>0)}
function fx(){for(let p of S.fx){p.x+=p.vx;p.y+=p.vy;p.vy+=.09;p.l--}S.fx=S.fx.filter(p=>p.l>0);for(let t of S.txt){t.y-=.55;t.l--}S.txt=S.txt.filter(t=>t.l>0);for(let r of S.ring){r.r+=2.4;r.l--}S.ring=S.ring.filter(r=>r.l>0)}
function hud(){if(!A||!B)return;$('p1Name').textContent=`P1 · ${BIBLE_ROSTER[A.id].name}`;$('p2Name').textContent=`P2 · ${BIBLE_ROSTER[B.id].name}`;$('p1HpText').textContent=`${Math.ceil(A.hp)} / ${A.max}`;$('p2HpText').textContent=`${Math.ceil(B.hp)} / ${B.max}`;$('p1HpBar').style.width=`${A.hp/A.max*100}%`;$('p2HpBar').style.width=`${B.hp/B.max*100}%`;$('p1UltBar').style.width=`${A.u}%`;$('p2UltBar').style.width=`${B.u}%`;$('p1Combo').classList.toggle('show',A.combo>1);$('p2Combo').classList.toggle('show',B.combo>1);$('p1Combo').querySelector('strong').textContent=A.combo;$('p2Combo').querySelector('strong').textContent=B.combo;document.querySelector('.round-info b').textContent=`第 ${S.r} 回合`;document.querySelector('.round-info small').textContent=`BO3 · ${S.sc[0]}-${S.sc[1]}`}
function meta(){let a=BIBLE_ROSTER[A.id],b=BIBLE_ROSTER[B.id];$('fightLoreTitle').textContent=`${a.name} vs ${b.name}`;$('fightLore').innerHTML=`<div><b>${a.name}</b><span>${a.role}</span><small>${a.facts.join(' · ')}</small><em>${a.anchor}</em></div><div><b>${b.name}</b><span>${b.role}</span><small>${b.facts.join(' · ')}</small><em>${b.anchor}</em></div>`}
function arena(){let g=X.createLinearGradient(0,0,0,H);g.addColorStop(0,'#171c25');g.addColorStop(.6,'#727b7e');g.addColorStop(1,'#2f271f');X.fillStyle=g;X.fillRect(0,0,W,H);X.fillStyle='#b7ab94';X.globalAlpha=.2;for(let i=0;i<7;i++){X.beginPath();X.moveTo(i*170,G);X.lineTo(i*170+75,310+Math.sin(i)*25);X.lineTo(i*170+150,G);X.fill()}X.globalAlpha=1;X.fillStyle='#4d3927';X.fillRect(0,G,W,H-G);X.fillStyle='#735739';X.fillRect(0,G,W,6);X.strokeStyle='#dfc47f55';X.setLineDash([4,8]);X.beginPath();X.moveTo(W/2,G-120);X.lineTo(W/2,G);X.stroke();X.setLineDash([])}
function drawF(f){if(f.inv>0&&Math.floor(f.inv/3)%2===0)return;let x=f.x+21,y=f.y+68;X.save();X.translate(x,y);X.scale(f.f,1);X.fillStyle='#0007';X.beginPath();X.ellipse(0,2,29,7,0,0,Math.PI*2);X.fill();X.fillStyle=K[f.id][4];X.fillRect(-18,-58,36,50);X.fillStyle='#c9a477';X.fillRect(-13,-81,26,23);X.fillStyle='#40342a';X.fillRect(-16,-87,32,10);if(f.id==='moses'){X.strokeStyle='#b99e70';X.lineWidth=4;X.beginPath();X.moveTo(22,-56);X.lineTo(27,-5);X.stroke()}if(f.id==='samson'){X.fillStyle='#2d231c';X.fillRect(-25,-88,50,20)}if(f.atk>0){X.fillStyle='#f2d69d';X.fillRect(16,-53,30,4)}X.restore()}
function drawFX(){for(let q of S.shot){X.fillStyle=q.k==='fire'?'#e28e4e':'#2e261d';X.beginPath();X.arc(q.x,q.y,6,0,7);X.fill();X.strokeStyle=q.k==='fire'?'#f1bd63':'#e2c17c';X.beginPath();X.moveTo(q.x-18,q.y);X.lineTo(q.x+18,q.y);X.stroke()}for(let r of S.ring){X.globalAlpha=r.l/16;X.strokeStyle=r.c;X.beginPath();X.arc(r.x,r.y,r.r,0,7);X.stroke()}X.globalAlpha=1;for(let p of S.fx){X.fillStyle=p.c;X.fillRect(p.x,p.y,3,3)}X.font='bold 14px sans-serif';X.textAlign='center';for(let t of S.txt){X.globalAlpha=Math.max(0,t.l/36);X.fillStyle=t.k==='d'?'#ffe7a3':t.k==='s'?'#f2d8a7':'#ffb7aa';X.fillText(t.t,t.x,t.y)}X.globalAlpha=1;X.textAlign='left'}
function update(dt){if(S.run){let d=S.hit?0.35:1;S.hit=Math.max(0,S.hit-dt);updateF(A,dt*d);updateF(B,dt*d);shots(dt*d);fx()}else fx();hud()}function draw(){X.clearRect(0,0,W,H);arena();if(A)drawF(A);if(B)drawF(B);drawFX();requestAnimationFrame(loop)}let last=performance.now();function loop(n){let dt=Math.min(1.5,(n-last)/16.67);last=n;update(dt);draw()}$("startBtn").onclick=start;$("rematchBtn").onclick=rematch;$("changeBtn").onclick=select;$("aboutBtn").onclick=()=>$("aboutDialog").showModal();$("closeAbout").onclick=()=>$("aboutDialog").close();picks();loop(performance.now());
