const { app, BrowserWindow, Menu } = require('electron');
const path = require('path');
const fs = require('fs');
const smoke = process.env.BIBLE_FIGHTER_SMOKE === '1';
let smokeLogPath = null;
function writeFatalLog(kind,error){try{const message=error instanceof Error?`${error.stack||error.message}`:String(error);fs.appendFileSync(path.join(app.getPath('userData'),'bible-fighter-runtime.log'),`[${new Date().toISOString()}] ${kind}\n${message}\n`,'utf8');}catch{}}
function writeSmokeTrace(stage,payload){if(!smoke)return;try{smokeLogPath ||= path.join(app.getPath('userData'),'bible-fighter-smoke.log');fs.appendFileSync(smokeLogPath,`[${new Date().toISOString()}] ${stage} ${typeof payload==='string'?payload:JSON.stringify(payload)}\n`,'utf8');}catch{}}
function failSmoke(stage,payload){writeSmokeTrace(stage,payload);app.exit(1);}
process.on('uncaughtException',e=>{writeFatalLog('uncaughtException',e);writeSmokeTrace('uncaughtException',e?.stack||e);if(smoke)app.exit(1);});
process.on('unhandledRejection',e=>{writeFatalLog('unhandledRejection',e);writeSmokeTrace('unhandledRejection',e?.stack||e);if(smoke)app.exit(1);});
function createWindow(){const win=new BrowserWindow({width:1280,height:820,minWidth:980,minHeight:700,backgroundColor:'#090807',title:'Bible Fighter',autoHideMenuBar:true,show:!smoke,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true,preload:path.join(__dirname,'preload-runtime.cjs')}});Menu.setApplicationMenu(null);win.webContents.on('did-fail-load',(_e,code,desc)=>{if(smoke)failSmoke('renderer-load-failed',{code,desc});});win.webContents.on('render-process-gone',(_e,details)=>{if(smoke)failSmoke('renderer-gone',details);});win.webContents.once('did-finish-load',()=>{if(!smoke)return;setTimeout(async()=>{try{
const probe=await win.webContents.executeJavaScript(`(()=>({version:window.BIBLE_FIGHTER_DESKTOP?.version||'',ready:document.readyState,cards1:document.querySelectorAll('#p1Grid .char-card').length,cards2:document.querySelectorAll('#p2Grid .char-card').length,startDisabled:!!document.querySelector('#startBtn')?.disabled,selection:!!window.BIBLE_FIGHTER_SELECTION_READY,verticalSlice:!!window.BIBLE_FIGHTER_VERTICAL_SLICE_READY,realCombat:!!window.BIBLE_FIGHTER_REAL_COMBAT_READY,combatCore:!!window.BIBLE_FIGHTER_COMBAT_CORE_READY,cooldown:!!window.BIBLE_FIGHTER_COOLDOWN_READY,runtimePolish:!!window.BIBLE_FIGHTER_RUNTIME_POLISH_READY,runtimePolishApi:!!window.BIBLE_FIGHTER_RUNTIME_POLISH_API,hud:!!document.querySelector('.combat-ui'),mission:!!document.querySelector('.mission-panel'),skills:!!document.querySelector('.skill-deck'),map:!!document.querySelector('.battle-map'),roster:typeof window.BIBLE_ROSTER==='object',missions:typeof window.BIBLE_MISSIONS==='object',codex:typeof window.BIBLE_CODEX==='object'}))()`,true);writeSmokeTrace('boot',probe);if(probe.version!=='1.5.1'||probe.ready!=='complete'||probe.cards1<6||probe.cards2<6||!probe.startDisabled||!probe.selection||!probe.verticalSlice||!probe.realCombat||!probe.combatCore||!probe.cooldown||!probe.runtimePolish||!probe.runtimePolishApi||!probe.hud||!probe.mission||!probe.skills||!probe.map||!probe.roster||!probe.missions||!probe.codex)return failSmoke('boot-failed',probe);
const selected=await win.webContents.executeJavaScript(`(()=>{const a=[...document.querySelectorAll('#p1Grid .char-card')][0],b=[...document.querySelectorAll('#p2Grid .char-card')][1];if(!a||!b)return {ok:false};a.click();b.click();return {ok:true,p1:document.querySelector('#p1Label')?.textContent||'',p2:document.querySelector('#p2Label')?.textContent||'',disabled:!!document.querySelector('#startBtn')?.disabled}})()`,true);if(!selected.ok||selected.p1!=='大卫'||selected.p2!=='摩西'||selected.disabled)return failSmoke('selection-failed',selected);
await win.webContents.executeJavaScript('window.start()',true);
const battle=await win.webContents.executeJavaScript(`new Promise(r=>setTimeout(()=>r({run:!!window.S.run,p1:window.A?.id||'',p2:window.B?.id||'',stage:window.BIBLE_FIGHTER_VERTICAL_SLICE_API?.snapshot?.()?.stage||'',slice:window.BIBLE_FIGHTER_VERTICAL_SLICE_API?.snapshot?.()||null,polish:window.BIBLE_FIGHTER_RUNTIME_POLISH_API?.snapshot?.()||null}),1800)`,true);writeSmokeTrace('vertical-slice',battle);if(!battle.run||battle.p1!=='david'||battle.p2!=='moses'||!battle.stage||!battle.slice||!battle.polish)return failSmoke('vertical-slice-failed',battle);
const damage=await win.webContents.executeJavaScript(`new Promise(resolve=>{window.A.x=window.B.x-54;window.A.f=1;const before=window.B.hp;window.BIBLE_FIGHTER_REAL_COMBAT_API.action('p1','attack');setTimeout(()=>resolve({before,after:window.B.hp,core:window.BIBLE_FIGHTER_COMBAT_CORE_API?.snapshot?.()||null,polish:window.BIBLE_FIGHTER_RUNTIME_POLISH_API?.snapshot?.()||null}),220)})`,true);writeSmokeTrace('damage',damage);if(!(damage.after<damage.before)||!damage.core||!damage.polish)return failSmoke('damage-failed',damage);
const skill=await win.webContents.executeJavaScript(`new Promise(resolve=>{window.A.x=window.B.x-70;window.A.f=1;const before=window.BIBLE_FIGHTER_COOLDOWN_API.snapshot().p1.s1;window.BIBLE_FIGHTER_REAL_COMBAT_API.action('p1','skill1');setTimeout(()=>resolve({before,after:window.BIBLE_FIGHTER_COOLDOWN_API.snapshot().p1.s1,shots:Array.isArray(window.S?.shots)?window.S.shots.length:0,model:window.BIBLE_FIGHTER_DAVID_MODEL_API?.snapshot?.()||null,polish:window.BIBLE_FIGHTER_RUNTIME_POLISH_API?.snapshot?.()||null}),150)})`,true);writeSmokeTrace('david-skill',skill);if(!(skill.after>0)||!(skill.shots>=0)||!skill.model||!skill.polish)return failSmoke('david-skill-failed',skill);
writeSmokeTrace('passed',{version:window.BIBLE_FIGHTER_DESKTOP?.version||'',verticalSlice:window.BIBLE_FIGHTER_VERTICAL_SLICE_API?.snapshot?.()||null,combatCore:window.BIBLE_FIGHTER_COMBAT_CORE_API?.snapshot?.()||null,polish:window.BIBLE_FIGHTER_RUNTIME_POLISH_API?.snapshot?.()||null,davidModel:skill.model});app.exit(0);
}catch(e){writeSmokeTrace('probe-exception',e?.stack||String(e));app.exit(1);}},700);});win.loadFile(path.join(__dirname,'..','playtest.html'));}
app.whenReady().then(()=>{createWindow();if(!smoke)app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();});});app.on('window-all-closed',()=>{if(!smoke&&process.platform!=='darwin')app.quit();});