const { app, BrowserWindow, Menu } = require('electron');
const path = require('path');
const fs = require('fs');
const smoke = process.env.BIBLE_FIGHTER_SMOKE === '1';
let smokeLogPath = null;
function writeFatalLog(kind,error){try{const message=error instanceof Error?`${error.stack||error.message}`:String(error);fs.appendFileSync(path.join(app.getPath('userData'),'bible-fighter-runtime.log'),`[${new Date().toISOString()}] ${kind}\n${message}\n`,'utf8');}catch{}}
function writeSmokeTrace(stage,payload){if(!smoke)return;try{smokeLogPath ||= path.join(app.getPath('userData'),'bible-fighter-smoke.log');fs.appendFileSync(smokeLogPath,`[${new Date().toISOString()}] ${stage} ${typeof payload==='string'?payload:JSON.stringify(payload)}\n`,'utf8');}catch{}}
function failSmoke(stage,payload){writeSmokeTrace(stage,payload);app.exit(1);}
process.on('uncaughtException',e=>{writeFatalLog('uncaughtException',e);writeSmokeTrace('uncaughtException',e?.stack||e);if(smoke)app.exit(1);});
process.on('unhandledRejection',e=>{writeFatalLog('unhandledRejection',e);writeSmokeTrace('unhandledRejection',e?.stack||e);if(smoke)app.exit(1);});
function createWindow(){const win=new BrowserWindow({width:1280,height:820,minWidth:980,minHeight:700,backgroundColor:'#090807',title:'Bible Fighter',autoHideMenuBar:true,show:!smoke,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true,preload:path.join(__dirname,'preload.cjs')}});Menu.setApplicationMenu(null);win.webContents.on('did-fail-load',(_e,code,desc)=>{if(smoke)failSmoke('renderer-load-failed',{code,desc});});win.webContents.on('render-process-gone',(_e,details)=>{if(smoke)failSmoke('renderer-gone',details);});win.webContents.once('did-finish-load',()=>{if(!smoke)return;setTimeout(async()=>{try{
const probe=await win.webContents.executeJavaScript(`(()=>({version:window.BIBLE_FIGHTER_DESKTOP?.version||'',ready:document.readyState,cards1:document.querySelectorAll('#p1Grid .char-card').length,cards2:document.querySelectorAll('#p2Grid .char-card').length,startDisabled:!!document.querySelector('#startBtn')?.disabled,selection:!!window.BIBLE_FIGHTER_SELECTION_READY,selectionShowcase:!!window.BIBLE_FIGHTER_SELECTION_SHOWCASE_READY,combatPresentation:!!window.BIBLE_FIGHTER_COMBAT_PRESENTATION_READY,davidShowcase:!!window.BIBLE_FIGHTER_DAVID_SHOWCASE_READY,davidModel:!!window.BIBLE_FIGHTER_DAVID_MODEL_READY,davidModelQuality:!!window.BIBLE_FIGHTER_DAVID_MODEL_QUALITY_READY,combatFeel:!!window.BIBLE_FIGHTER_COMBAT_FEEL_READY,davidCombo:!!window.BIBLE_FIGHTER_DAVID_COMBO_READY,davidInteraction:!!window.BIBLE_FIGHTER_DAVID_INTERACTION_READY,davidPolish:!!window.BIBLE_FIGHTER_DAVID_POLISH_READY,hud:!!document.querySelector('.combat-ui'),mission:!!document.querySelector('.mission-panel'),skills:!!document.querySelector('.skill-deck'),map:!!document.querySelector('.battle-map'),roster:typeof window.BIBLE_ROSTER==='object',missions:typeof window.BIBLE_MISSIONS==='object',codex:typeof window.BIBLE_CODEX==='object',quality:!!window.BIBLE_FIGHTER_QUALITY_READY}))()`,true);writeSmokeTrace('boot',probe);if(probe.version!=='1.4.4'||probe.ready!=='complete'||probe.cards1<6||probe.cards2<6||!probe.startDisabled||!probe.selection||!probe.selectionShowcase||!probe.combatPresentation||!probe.davidShowcase||!probe.davidModel||!probe.davidModelQuality||!probe.combatFeel||!probe.davidCombo||!probe.davidInteraction||!probe.davidPolish||!probe.hud||!probe.mission||!probe.skills||!probe.map||!probe.roster||!probe.missions||!probe.codex||!probe.quality)return failSmoke('boot-failed',probe);
const selected=await win.webContents.executeJavaScript(`(()=>{const a=[...document.querySelectorAll('#p1Grid .char-card')][0],b=[...document.querySelectorAll('#p2Grid .char-card')][1];if(!a||!b)return {ok:false};a.click();b.click();return {ok:true,p1:document.querySelector('#p1Label')?.textContent||'',p2:document.querySelector('#p2Label')?.textContent||'',disabled:!!document.querySelector('#startBtn')?.disabled}})()`,true);writeSmokeTrace('selection',selected);if(!selected.ok||selected.p1!=='大卫'||selected.p2!=='摩西'||selected.disabled)return failSmoke('selection-failed',selected);
await win.webContents.executeJavaScript(`window.start()`,true);const started=await win.webContents.executeJavaScript(`new Promise(r=>setTimeout(()=>r({run:!!window.S.run,p1:window.A?.id||'',p2:window.B?.id||'',battle:!document.querySelector('#battleScreen')?.classList.contains('hidden'),presentation:!!window.BIBLE_FIGHTER_COMBAT_PRESENTATION_READY,feel:!!window.BIBLE_FIGHTER_COMBAT_FEEL_READY,combo:!!window.BIBLE_FIGHTER_DAVID_COMBO_READY,model:!!window.BIBLE_FIGHTER_DAVID_MODEL_READY,modelQuality:!!window.BIBLE_FIGHTER_DAVID_MODEL_QUALITY_READY,interaction:!!window.BIBLE_FIGHTER_DAVID_INTERACTION_READY,polish:!!window.BIBLE_FIGHTER_DAVID_POLISH_READY}))(),2400)`,true);writeSmokeTrace('battle-start',started);if(!started.run||started.p1!=='david'||started.p2!=='moses'||!started.battle||!started.presentation||!started.feel||!started.combo||!started.model||!started.modelQuality||!started.interaction||!started.polish)return failSmoke('battle-start-failed',started);
const combat=await win.webContents.executeJavaScript(`(()=>({objective:document.querySelector('#combatObjective span')?.textContent||'',round:document.querySelector('#cpRound')?.textContent||'',score:document.querySelector('#cpScore')?.textContent||'',stage:document.querySelector('#cpStage')?.textContent||'',state:document.querySelector('#combatState')?.textContent||''}))()`,true);writeSmokeTrace('combat-presentation',combat);if(!combat.objective||!combat.round||!combat.score||!combat.stage)return failSmoke('combat-presentation-failed',combat);
const damage=await win.webContents.executeJavaScript(`new Promise(resolve=>{window.A.x=window.B.x-54;window.A.f=1;const before=window.B.hp;window.act('p1','a');setTimeout(()=>resolve({before,after:window.B.hp,combo:window.BIBLE_FIGHTER_DAVID_COMBO_API?.snapshot?.(),model:window.BIBLE_FIGHTER_DAVID_MODEL_API?.snapshot?.(),polish:window.BIBLE_FIGHTER_DAVID_POLISH_API?.snapshot?.()}),220)})`,true);writeSmokeTrace('damage',damage);if(!(damage.after<damage.before)||!damage.combo||!damage.model||damage.model.action!=='attack'||!damage.polish||!(damage.polish.hitCount>0))return failSmoke('damage-failed',damage);
const davidSkill=await win.webContents.executeJavaScript(`new Promise(resolve=>{window.A.x=window.B.x-70;window.A.f=1;window.act('p1','s1');setTimeout(()=>resolve({model:!!window.BIBLE_FIGHTER_DAVID_MODEL_READY,modelQuality:!!window.BIBLE_FIGHTER_DAVID_MODEL_QUALITY_READY,interaction:!!window.BIBLE_FIGHTER_DAVID_INTERACTION_READY,polish:!!window.BIBLE_FIGHTER_DAVID_POLISH_READY,shots:Array.isArray(window.S?.shots)?window.S.shots.length:0,action:window.BIBLE_FIGHTER_DAVID_MODEL?.action||'',skillPhase:window.BIBLE_FIGHTER_DAVID_MODEL?.skillPhase||'',lastSkill:window.BIBLE_FIGHTER_DAVID_MODEL?.lastSkill||'',interactionState:window.BIBLE_FIGHTER_DAVID_INTERACTION_API?.snapshot?.(),polishState:window.BIBLE_FIGHTER_DAVID_POLISH_API?.snapshot?.()}),120)})`,true);writeSmokeTrace('david-skill',davidSkill);if(!davidSkill.model||!davidSkill.modelQuality||!davidSkill.interaction||!davidSkill.polish||davidSkill.lastSkill!=='投石索'||!(davidSkill.shots>0))return failSmoke('david-skill-failed',davidSkill);
writeSmokeTrace('passed',{version:window.BIBLE_FIGHTER_DESKTOP?.version||'',quality:window.BIBLE_FIGHTER_QUALITY?.snapshot?.()||null,combatFeel:window.BIBLE_FIGHTER_COMBAT_FEEL,davidCombo:damage.combo,davidModel:damage.model,davidInteraction:davidSkill.interactionState,davidPolish:davidSkill.polishState});app.exit(0);
}catch(e){writeSmokeTrace('probe-exception',e?.stack||String(e));app.exit(1);}},700);});win.loadFile(path.join(__dirname,'..','playtest.html'));}
app.whenReady().then(()=>{createWindow();if(!smoke)app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();});});app.on('window-all-closed',()=>{if(!smoke&&process.platform!=='darwin')app.quit();});
