import { existsSync, readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
const required = ['playtest.html','style.css','game7.js','game8.js','game9.js','game10.js','game11.js','game12.js','game13.js','game14.js','game15.js','game19.js','game20.js','game21.js','game22.js','game23.js','game24.js','game25.js','game26.js','game27.js','game28.js','game29.js','game30.js','game31.js','game32.js','game33.js','game34.js','game35.js','game36.js','game37.js','game38.js','game39.js','game40.js','game8.css','game20.css','game21.css','game22.css','game23.css','game34.css','game37.css','game38.css','data/characters.js','data/supports.js','data/missions.js','data/codex.js','data/update-manifest.js','data/update.json','electron/main.cjs','electron/preload.cjs','Playtest-Windows.bat'];
const missing=required.filter((file)=>!existsSync(file)); if(missing.length){console.error('Missing required build files:\n'+missing.join('\n'));process.exit(1);}
const game7=readFileSync('game7.js','utf8'); if(game7.trim().length<2000){console.error('Build validation failed: game7.js unexpectedly small.');process.exit(1);}
for(const marker of ['window.BIBLE_FIGHTER_SELECTION_READY','window.refreshSelect','window.start','window.attack','window.update','window.drawFx'])if(!game7.includes(marker)){console.error(`game7 marker missing: ${marker}`);process.exit(1);}
for(const marker of ['BIBLE_FIGHTER_STABILITY_READY','BIBLE_FIGHTER_CLEAR_INPUT','BIBLE_FIGHTER_TRIGGER_HITSTOP','bounds','separation'])if(!readFileSync('game32.js','utf8').includes(marker)){console.error(`game32 marker missing: ${marker}`);process.exit(1);}
for(const marker of ['BIBLE_FIGHTER_MATCH_READY','BIBLE_FIGHTER_RESET_INPUT','BIBLE_FIGHTER_MATCH_SYNC','epoch'])if(!readFileSync('game33.js','utf8').includes(marker)){console.error(`game33 marker missing: ${marker}`);process.exit(1);}
for(const marker of ['BIBLE_FIGHTER_UPDATE_CENTER_READY','UPDATE CENTER','检查更新'])if(!readFileSync('game34.js','utf8').includes(marker)){console.error(`game34 marker missing: ${marker}`);process.exit(1);}
for(const marker of ['BIBLE_FIGHTER_QUALITY_READY','BIBLE_FIGHTER_QUALITY','targetFps','frameMs'])if(!readFileSync('game35.js','utf8').includes(marker)){console.error(`game35 marker missing: ${marker}`);process.exit(1);}
for(const marker of ['BIBLE_FIGHTER_DAVID_SHOWCASE_READY','DAVID ·','牧者连段','远程确认','突进追击','终结演出'])if(!readFileSync('game36.js','utf8').includes(marker)){console.error(`game36 David showcase marker missing: ${marker}`);process.exit(1);}
for(const marker of ['BIBLE_FIGHTER_SELECTION_SHOWCASE_READY','CHARACTER SHOWCASE','pixel-head','stage-preview'])if(!readFileSync('game37.js','utf8').includes(marker)){console.error(`game37 selection showcase marker missing: ${marker}`);process.exit(1);}
for(const marker of ['BIBLE_FIGHTER_COMBAT_PRESENTATION_READY','combat-topline','combat-objective','combat-status-line'])if(!readFileSync('game38.js','utf8').includes(marker)){console.error(`game38 combat presentation marker missing: ${marker}`);process.exit(1);}
for(const marker of ['BIBLE_FIGHTER_COMBAT_FEEL_READY','inputBufferFrames','hitStopFrames','perfectInputCount'])if(!readFileSync('game39.js','utf8').includes(marker)){console.error(`game39 combat feel marker missing: ${marker}`);process.exit(1);}
for(const marker of ['BIBLE_FIGHTER_DAVID_COMBO_READY','inputBuffer','cancelWindow','landingGrace','airChaseReady'])if(!readFileSync('game40.js','utf8').includes(marker)){console.error(`game40 David combo marker missing: ${marker}`);process.exit(1);}
if(!readFileSync('data/update.json','utf8').includes('1.3.3')){console.error('update.json version missing 1.3.3');process.exit(1);}
if(!readFileSync('data/update-manifest.js','utf8').includes('1.3.3')){console.error('update-manifest version missing 1.3.3');process.exit(1);}
const preload=readFileSync('electron/preload.cjs','utf8'); for(const marker of ['1.3.3','game34.js','game34.css','data/update-manifest.js'])if(!preload.includes(marker)){console.error(`preload update mount missing: ${marker}`);process.exit(1);}
const pkg=JSON.parse(readFileSync('package.json','utf8')); if(pkg.version!=='1.3.3'){console.error(`package version drift: ${pkg.version}`);process.exit(1);} if(!(pkg.build?.files||[]).includes('game37.js')||!(pkg.build?.files||[]).includes('game38.js')||!(pkg.build?.files||[]).includes('game39.js')||!(pkg.build?.files||[]).includes('game40.js')){console.error('electron-builder package files omit combat presentation/feel/combo layers');process.exit(1);}
for(const file of required.filter((f)=>/\.js$/.test(f)).concat(['electron/main.cjs','electron/preload.cjs'])){const result=spawnSync(process.execPath,['--check',file],{stdio:'inherit'});if(result.status!==0)process.exit(result.status??1);}
console.log('Build validation passed: 2P combat + stage + David showcase + presentation + responsive combat feel + David combo quality intact.');
