import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
const root=process.cwd();const fail=message=>{console.error(`Runtime validation failed: ${message}`);process.exit(1);};
const htmlPath=resolve(root,'playtest.html');if(!existsSync(htmlPath))fail('playtest.html is missing');const html=readFileSync(htmlPath,'utf8');const scripts=[...html.matchAll(/<script\s+src=["']([^"']+)["'][^>]*><\/script>/gi)].map(m=>m[1]);
const expectedRuntime=['data/characters.js','data/supports.js','data/missions.js','data/codex.js','game7.js','game19.js','game20.js','game21.js','game22.js','game23.js','game24.js','game25.js','game26.js','game27.js','game28.js','game29.js','game30.js','game31.js','game32.js','game33.js','game35.js','game36.js','game37.js','game38.js','game39.js','game40.js','game41.js','game42.js','game43.js','game44.js','game45.js'];
for(const name of expectedRuntime)if(!scripts.includes(name))fail(`missing required runtime script: ${name}`);
const baseIndex=scripts.indexOf('game7.js');for(const name of ['data/characters.js','data/supports.js','data/missions.js','data/codex.js'])if(scripts.indexOf(name)>baseIndex)fail(`${name} must load before combat engine`);
for(let i=20;i<=33;i++)if(!(scripts.indexOf(`game${i}.js`)>scripts.indexOf(`game${i-1}.js`)))fail(`combat layer order invalid at game${i}.js`);
const order=[['game35.js','game33.js'],['game36.js','game35.js'],['game37.js','game36.js'],['game38.js','game37.js'],['game39.js','game38.js'],['game40.js','game39.js'],['game41.js','game40.js'],['game42.js','game41.js'],['game43.js','game42.js'],['game44.js','game43.js'],['game45.js','game44.js']];for(const[a,b]of order)if(!(scripts.indexOf(a)>scripts.indexOf(b)))fail(`runtime load order invalid: ${a} after ${b}`);
const styles=[...html.matchAll(/<link\s+rel=["']stylesheet["']\s+href=["']([^"']+)["'][^>]*>/gi)].map(m=>m[1]);for(const name of ['game20.css','game21.css','game22.css','game23.css','game37.css','game38.css'])if(!styles.includes(name))fail(`missing required stylesheet: ${name}`);
for(const src of scripts){if(/^https?:\/\//i.test(src)||src.startsWith('//'))fail(`remote dependency not allowed: ${src}`);if(!existsSync(resolve(root,src)))fail(`missing script: ${src}`);}for(const src of styles){if(/^https?:\/\//i.test(src)||src.startsWith('//'))fail(`remote stylesheet not allowed: ${src}`);if(!existsSync(resolve(root,src)))fail(`missing stylesheet: ${src}`);}
const game45=readFileSync(resolve(root,'game45.js'),'utf8');if(!game45.includes('game46.js')||!game45.includes('bibleCombatCore'))fail('game45 does not dynamically mount combat core');if(!readFileSync(resolve(root,'game46.js'),'utf8').includes('BIBLE_FIGHTER_COMBAT_CORE_READY'))fail('game46 combat core marker missing');
const preload=readFileSync(resolve(root,'electron/preload.cjs'),'utf8');for(const marker of ['game34.js','game34.css','game43.js','game44.js','game45.js','data/update-manifest.js','1.4.6'])if(!preload.includes(marker))fail(`desktop runtime mount missing: ${marker}`);
for(const marker of ['id="selectScreen"','id="battleScreen"','id="game"','id="startBtn"'])if(!html.includes(marker))fail(`missing required UI marker: ${marker}`);
const pkg=JSON.parse(readFileSync(resolve(root,'package.json'),'utf8'));if(pkg.version!=='1.4.6')fail(`package version drift: ${pkg.version}`);const buildFiles=pkg.build?.files??[];for(const required of ['playtest.html','game34.js','game34.css','game35.js','game36.js','game37.js','game37.css','game38.js','game38.css','game39.js','game40.js','game41.js','game42.js','game43.js','game44.js','game45.js','game46.js','data/**/*','electron/**/*'])if(!buildFiles.includes(required))fail(`electron-builder package files omit ${required}`);
console.log(`Runtime validation passed: ${scripts.length} boot scripts + dynamically mounted combat core 2.0 + real P1/P2 interaction + David model/skills + projectile/hit + combat polish + cooldown timing + lifecycle hardening + combo + combat feel intact.`);
