import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
const root=process.cwd(); const fail=(message)=>{console.error(`Runtime validation failed: ${message}`);process.exit(1);};
const htmlPath=resolve(root,'playtest.html'); if(!existsSync(htmlPath))fail('playtest.html is missing');
const html=readFileSync(htmlPath,'utf8');
const scripts=[...html.matchAll(/<script\s+src=["']([^"']+)["'][^>]*><\/script>/gi)].map((m)=>m[1]);
const expectedRuntime=['data/characters.js','data/supports.js','data/missions.js','data/codex.js','game7.js','game19.js','game20.js','game21.js','game22.js','game23.js','game24.js','game25.js','game26.js','game27.js','game28.js','game29.js','game30.js','game31.js','game32.js','game33.js','game35.js'];
for(const name of expectedRuntime)if(!scripts.includes(name))fail(`missing required runtime script: ${name}`);
const baseIndex=scripts.indexOf('game7.js'); for(const name of ['data/characters.js','data/supports.js','data/missions.js','data/codex.js'])if(scripts.indexOf(name)>baseIndex)fail(`${name} must load before combat engine`);
for(let i=20;i<=33;i++)if(!(scripts.indexOf(`game${i}.js`)>scripts.indexOf(`game${i-1}.js`)))fail(`combat layer order invalid at game${i}.js`);
if(!(scripts.indexOf('game35.js')>scripts.indexOf('game33.js')))fail('quality layer must load after match lifecycle');
const styles=[...html.matchAll(/<link\s+rel=["']stylesheet["']\s+href=["']([^"']+)["'][^>]*>/gi)].map((m)=>m[1]);
for(const name of ['game20.css','game21.css','game22.css','game23.css'])if(!styles.includes(name))fail(`missing required stylesheet: ${name}`);
for(const src of scripts){if(/^https?:\/\//i.test(src)||src.startsWith('//'))fail(`remote dependency not allowed: ${src}`);if(!existsSync(resolve(root,src)))fail(`missing script: ${src}`);} for(const src of styles){if(/^https?:\/\//i.test(src)||src.startsWith('//'))fail(`remote stylesheet not allowed: ${src}`);if(!existsSync(resolve(root,src)))fail(`missing stylesheet: ${src}`);}
const preload=readFileSync(resolve(root,'electron/preload.cjs'),'utf8'); for(const marker of ['game34.js','game34.css','data/update-manifest.js','1.2.9'])if(!preload.includes(marker))fail(`desktop update mount missing: ${marker}`);
for(const marker of ['id="selectScreen"','id="battleScreen"','id="game"','id="startBtn"'])if(!html.includes(marker))fail(`missing required UI marker: ${marker}`);
const pkg=JSON.parse(readFileSync(resolve(root,'package.json'),'utf8')); if(pkg.version!=='1.2.9')fail(`package version drift: ${pkg.version}`); const buildFiles=pkg.build?.files??[];
for(const required of ['playtest.html','game34.js','game34.css','game35.js','data/**/*','electron/**/*'])if(!buildFiles.includes(required))fail(`electron-builder package files omit ${required}`);
for(const [file,marker,label] of [['game23.js','BIBLE_FIGHTER_BRIEFING_READY','briefing'],['game24.js','BIBLE_FIGHTER_COMBAT_FRAMES_READY','combat frame'],['game25.js','BIBLE_FIGHTER_FRAME_RULES_READY','frame rules'],['game26.js','BIBLE_FIGHTER_DAVID_ART_READY','David art'],['game27.js','BIBLE_FIGHTER_DAVID_IMPACT_READY','David impact'],['game28.js','BIBLE_FIGHTER_MULTIPLAYER_READY','local multiplayer'],['game29.js','BIBLE_FIGHTER_STAGE_READY','2D stage'],['game30.js','BIBLE_FIGHTER_CORE_CHARACTERS_READY','core fighters'],['game31.js','BIBLE_FIGHTER_READABILITY_READY','readability'],['game32.js','BIBLE_FIGHTER_STABILITY_READY','stability'],['game33.js','BIBLE_FIGHTER_MATCH_READY','match lifecycle'],['game35.js','BIBLE_FIGHTER_QUALITY_READY','quality runtime']])if(!readFileSync(resolve(root,file),'utf8').includes(marker))fail(`${label} runtime marker missing`);
for(const marker of ['1.2.9','stable','Global Quality Runtime + Playable Entry'])if(!readFileSync(resolve(root,'data/update.json'),'utf8').includes(marker))fail(`update.json marker missing: ${marker}`);
console.log(`Runtime validation passed: ${scripts.length} HTML scripts + update/quality layers + 2P/stages/match lifecycle intact.`);
